### ISSUE TITLE
Add Search Filters

### ISSUE THREAD

**Issue by jmcsmith** [jmcsmith/MTGCards#15]
Add ability to filter search by the following 
- Type
- Sub Type
- Super Type
- Color
- Legality
- Set

**Comment by Topper97** [comment]
Add filter by 

- CMC
- A specific number of a given mana symbol
- Color identity 
- Power 
- Toughness 
- Loyalty

**Comment by Topper97** [comment]
Be able to search by keyword both in the title and/or the text box. Not the flavor text.

**Comment by jmcsmith** [comment]
added the following in 15d0f796ce8dd22b66cad53cbf6af5ce9b3967fe
- Type
- Sub Type
- Super Type
- Color
- Legality
- Set

**Comment by jmcsmith** [comment]
closing this issue. new issue added in Release 1.1
