### ISSUE TITLE
Color Identity

### ISSUE THREAD

**Issue by Topper97** [jmcsmith/MTGCards#54]
If I search for cards with white color identity returns cards who's color identity is greater then just white.
Ex Abzan Banner color identity is WBG not W
can't run this in a commander deck with a mono white commander

**Comment by jmcsmith** [comment]
Results are if the color identity contains any of the ones selected. 
Maybe an any/all toggle option?

**Comment by Topper97** [comment]
By definition of color identity searching for W should not return Abzan Banner because it is more then just white

**Comment by jmcsmith** [comment]
So color identity should return only cards where the color identity fits in what is selected?

**Comment by Topper97** [comment]
Yes, color identity should return all cards with color identity <= what is searched for.
so searching for WBG should return all cards that are W,B,G,WB,WG,BG,colorless,WBG
