### ISSUE TITLE
Collection screen is very plain

### ISSUE THREAD

**Issue by jmcsmith** [jmcsmith/MTGCards#60]
Collection screen needs a designer 😕 ![Image](https://i.imgur.com/BEBTWcQ.jpg)

**Comment by Topper97** [comment]
Move the Search to the top so you don't have to scroll down to be able to search

**Comment by jmcsmith** [comment]
Make Deck Cells colored like card cells?

**Comment by jmcsmith** [comment]
Changed to sidebar on iPad and Mac and inset grouped on iPhone.
